### ISSUE TITLE
[FEATURE REQUEST] Iterate through a list or wildcard instead of choosing randomly

### ISSUE THREAD

**Issue by johnbrownlow** [Stability-AI/StableSwarmUI#321] opened 2024-04-27 14:04 UTC
Not sure if I'm missing how to do this but...

<random:> or the <wildcard:> currently choose randomly.

Ideally I would like to be able to iterate though a list sequentially, for example 

<for: dog, cat, fox, chicken, rat, monkey> 

would produce

dog
cat
fox
chicken
rat
monkey

in order. 

Same thing with a wildcard file where it would choose the prompts in order

An added bonus would be to be able to choose how many of each element to produce, ie the above list could produce 3 iterations of each element

dog
dog
dog
cat
cat
cat

and so on, which would allow you to batch in a useful way.

**Comment by mcmonkey4eva** [comment] 2024-04-28 03:59
Duplicate of https://github.com/Stability-AI/StableSwarmUI/issues/295

**Closed by mcmonkey4eva** 2024-04-28 03:59 UTC
