### ISSUE TITLE
Error generating images via auto_webui_selfstart (automatic1111)

### ISSUE THREAD

**Issue by rugabunda** [Stability-AI/StableSwarmUI#104] opened 2023-09-16 20:40 UTC
Also vram usage is at 98%, loading only deliberate_v2.safetensors, (2gb). Initially the auto111 webui loaded an xl model, (resulted in 84% ram usage), I switched to deliberate in stableswarm, and that was reflected in auto111, however the ram usage jumped higher, to 98.8%. Even after switching the model inside auto111 webui itself.
 
/w --loglevel debug

```
13:37:21.749 [Init] Self-Start AutoWebUI on port 7828 is loading...
13:37:37.986 [Init] Self-Start AutoWebUI on port 7828 started.
13:39:00.827 [Init] Self-Start ScorersExtension on port 7829 is loading...
13:39:00.975 [Info] Self-Start ScorersExtension on port 7829 unexpectedly exited (if something failed, launch with `--loglevel debug` to see why!)
13:39:00.975 [Info] Self-Start ScorersExtension on port 7829 had errors before shutdown:
ScorersExtension error: Traceback (most recent call last):
ScorersExtension error:   File "D:\AI\Image\StableSwarmUI\src\BuiltinExtensions\Scorers\scorer_engine.py", line 5, in <module>
ScorersExtension error:     from transformers import AutoProcessor, AutoModel
ScorersExtension error: ModuleNotFoundError: No module named 'transformers'

13:39:09.949 [Error] Internal error processing T2I request: System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. (localhost:7829))
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:7829)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at StableSwarmUI.Builtin_ScorersExtension.ScorersExtension.DoPost(String url, JObject data) in D:\AI\Image\StableSwarmUI\src\BuiltinExtensions\Scorers\ScorersExtension.cs:line 105
   at StableSwarmUI.Builtin_ScorersExtension.ScorersExtension.DoScore(Image image, String prompt, String scorer) in D:\AI\Image\StableSwarmUI\src\BuiltinExtensions\Scorers\ScorersExtension.cs:line 111
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at StableSwarmUI.Builtin_ScorersExtension.ScorersExtension.PostGenEvent(PostGenerationEventParams p) in D:\AI\Image\StableSwarmUI\src\BuiltinExtensions\Scorers\ScorersExtension.cs:line 137
   at StableSwarmUI.Text2Image.T2IEngine.<>c__DisplayClass8_1.<CreateImageTask>g__handleImage|1(Image img) in D:\AI\Image\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 131
   at StableSwarmUI.Text2Image.T2IEngine.<>c__DisplayClass8_1.<CreateImageTask>b__3(Object obj) in D:\AI\Image\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 155
   at StableSwarmUI.Backends.AbstractT2IBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in D:\AI\Image\StableSwarmUI\src\Backends\AbstractT2IBackend.cs:line 40
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages) in D:\AI\Image\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 151
```

**Comment by rugabunda** [comment] 2023-09-16 20:44
Is there a means of setting `set XFORMERS_PACKAGE=xformers==0.0.22.dev612` via your commandline argument option?

**Comment by rugabunda** [comment] 2023-09-16 20:46
If you delete the a running backend, would be nice if it was killed also.

**Comment by mcmonkey4eva** [comment] 2023-09-16 22:11
- It does kill the process if you delete a self-start backend (unless something has gone critically wrong)
- You can set complicatedy custom launch things in auto webui's files (you can link the self-start to webui-user if you edit the commandline_args line to be `set COMMANDLINE_ARGS=%*`)
- you have an error from trying to use [Scorers](https://github.com/Stability-AI/StableSwarmUI/blob/master/src/BuiltinExtensions/Scorers/README.md) which is a placeholder for now and requires manual install if you want to use it (will be cleaned up/automated in the future), you should probably just un-toggle the scoring parameter.
- If you're extremely tight on RAM you'll probably be happier with Comfy as the backend, it's generally better at memory management

**Comment by rugabunda** [comment] 2023-09-17 00:54
> * It does kill the process if you delete a self-start backend (unless something has gone critically wrong)

test

> * You can set complicatedy custom launch things in auto webui's files (you can link the self-start to webui-user if you edit the commandline_args line to be `set COMMANDLINE_ARGS=%*`)
> * you have an error from trying to use [Scorers](https://github.com/Stability-AI/StableSwarmUI/blob/master/src/BuiltinExtensions/Scorers/README.md) which is a placeholder for now and requires manual install if you want to use it (will be cleaned up/automated in the future), you should probably just un-toggle the scoring parameter.

I wasn't using scores

> * If you're extremely tight on RAM you'll probably be happier with Comfy as the backend, it's generally better at memory management

**Comment by mcmonkey4eva** [comment] 2023-09-17 13:00
`I wasn't using scores` you must've enabled it by accident then? The error is very much in trying to load `ScorersExtension`.

`edited webui-user.bat, added that string, but it didn't work.` oops, very old safety check I forgot was there. I updated it and tested to make sure it actually works as intended now.

`didn't work the last i tried` I did some testing - while it does indeed kill self-start processes like I said... apparently auto webui doesn't care about merely being killed and remains alive anyway. That's, uh, new. Anyway I committed a much more aggressive process termination routine that in my testing does manage to prevent zombies.

**Closed by mcmonkey4eva** 2023-09-17 13:00 UTC

**Comment by rugabunda** [comment] 2023-09-17 23:07
> `I wasn't using scores` you must've enabled it by accident then? The error is very much in trying to load `ScorersExtension`.
> 
> `edited webui-user.bat, added that string, but it didn't work.` oops, very old safety check I forgot was there. I updated it and tested to make sure it actually works as intended now.
> 
> `didn't work the last i tried` I did some testing - while it does indeed kill self-start processes like I said... apparently auto webui doesn't care about merely being killed and remains alive anyway. That's, uh, new. Anyway I committed a much more aggressive process termination routine that in my testing does manage to prevent zombies.

Code master, you're right on top of it.

Thank you.

**Comment by rugabunda** [comment] 2023-09-17 23:13
Yup.... webui-user.bat is loading.  I'll push out some photos, see what happens.

Yes Auto111 it working, slowly but working. perhaps I did have scoring on last time.

`Generated an image in 18.91 (prep) and 76.37 (gen) seconds` 
`16:12:55.134 [Info] Generated an image in 86.53 (prep) and 70.38 (gen) seconds`

just using sdxl base alone, usually takes 15...
