### ISSUE TITLE
how to do controlnet reference?

### ISSUE THREAD

**Issue by FemBoxbrawl** [Stability-AI/StableSwarmUI#368] opened 2024-06-03 08:50 UTC
I don't know how to do reference_only or something like that, is there a way to implement it if not done already?

**Comment by mcmonkey4eva** [comment] 2024-06-03 21:40
"controlnet reference" isn't actually a controlnet, it's just merged into that extension for auto webui --- to use in swarm you'd need to find a Comfy node for it, which last i looked iirc there's only experimental/hacky ones not great options. See also earlier thread here https://github.com/Stability-AI/StableSwarmUI/issues/176

**Closed by mcmonkey4eva** 2024-06-03 21:40 UTC

**Comment by Sisimshow** [comment] 2024-06-04 01:52
I too would be interested in this. It does work for Stability Matrix Inference interface (which uses ComfyUI) so it can be done. The results aren't the same as using Revision or IPAdapter, I'd say for replicating, say, the outfit of a character without a Lora, it's much better. This is one of the last things keeping me from jumping from A1111/Forge to StableSwarm because I use it for making variants of my D&D character art. 

All that said, I don't want to sound overly assertive, just wanted to put out there that there is some demand for this feature and it's not simply an outdated version of Revision or IPadapter.

**Comment by mcmonkey4eva** [comment] 2024-06-04 02:01
`It does work for Stability Matrix Inference interface (which uses ComfyUI) so it can be done` do you have a reference to the comfy node they used for it?

**Comment by Sisimshow** [comment] 2024-06-04 02:10
Yes, Inference_Core_FerenceOnlySimple. Here is a picture made with Stability Matrix using Reference Only and put into ComfyUI. 
[workflow.json](https://github.com/user-attachments/files/15541589/workflow.json)
![2024-06-03_21-42-06-AutismMixSDXLPony-1322834208](https://github.com/Stability-AI/StableSwarmUI/assets/126213271/8abba1b2-8b35-44bc-a27e-023738dab860)

**Comment by Sisimshow** [comment] 2024-06-04 02:11
Sorry for the anime

**Comment by mcmonkey4eva** [comment] 2024-06-04 02:18
`Inference_Core_ReferenceOnlySimple` appears to correspond to <https://github.com/LykosAI/ComfyUI-Inference-Core-Nodes/blob/main/src/inference_core_nodes/comfyui_experiments/reference_only.py> which is Inference's wonky broken import of <https://github.com/comfyanonymous/ComfyUI_experiments/blob/master/reference_only.py> which as noted in the prior thread didn't seem to generally actually work as intended last I tested it

I guess I'll have to re-test

**Comment by Sisimshow** [comment] 2024-06-04 02:21
I appreciate the effort :) I hope this doesn't waste too much of your time good man

**Comment by mcmonkey4eva** [comment] 2024-06-04 03:00
I'm very confused what happened last year when trying it then, but it indeed works now!

I've enabled `ReferenceOnly` via comfy's experiment code (slightly adapted), with a new `Use Reference Only` param under ReVision (ie drag an image to prompt box and it will be included as an option)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/4f5df1f2-9412-4fa0-b8ce-0ffdefedff27)

**Comment by Sisimshow** [comment] 2024-06-04 08:49
Niceness! Thank you so much!
